config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

  def contact

  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<header>
  <h1>BETA BLOG</h1>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
  </ul>
  <div>
    <h2>About</h2>
  </div>
</header>

app/views/pages/contact.html.erb
<header>
  <h1>BETA BLOG</h1>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
  </ul>
  <div>
    <h2>Contact</h2>
  </div>
</header>

app/views/pages/home.html.erb
<header>
  <h1>BETA BLOG</h1>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
  </ul>
  <div>
    <h2>About</h2>
  </div>
</header>